"""posts table

Revision ID: 711d7f745dc9
Revises: 582c88e5df20
Create Date: 2020-03-08 17:40:00.685054

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '711d7f745dc9'
down_revision = '582c88e5df20'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=120), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_body'), 'posts', ['body'], unique=True)
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_index(op.f('ix_posts_body'), table_name='posts')
    op.drop_table('posts')
    # ### end Alembic commands ###
